name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HG }}  # or secrets.HG if that's what you used

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.email "karthik773322000044@gmail.com"
          git config --global user.name "karthiksharma"

      - name: Set up Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Track model files (if needed)
        run: |
          git lfs track "*.pt" "*.bin" "*.model"  # Adjust patterns as needed
          git add .gitattributes || true

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://karthiksharma:${HF_TOKEN}@huggingface.co/spaces/karthiksharma/demo2.git
          git push hf main --force
