name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: |
          git config --global user.email "karthik773322000044@gmail.com"
          git config --global user.name "karthiksharma"
          git remote add hf https://karthiksharma:${HF_TOKEN}@huggingface.co/spaces/karthiksharma/demo2.git
          git push --force hf main
